In [3]:
import numpy as np
import h5py

In [3]:
#(1001,355,266) t=1001


with h5py.File(hdfpath,'r') as f:
    # ファイルオブジェクトをイテレートするとファイル直下のオブジェクト名を返す
    data=f['/Object'][0]
print(data.shape)    #>>3次元

(1001, 355, 266)


In [4]:
j=0
last=[]
for i in data[0]:
    #print(i,"\n\n")
    last.append(i)
    


In [10]:
k=0
#以下の形でtime-stepごとに266*355を取り出せる　>>イメージ輪切り
for i in data:
    if k == 1000:
        print(data[i][0][0])
        a = data[i][0][0]
    k+=1
print(k)    
print(a.shape)

[[317 317 318 ... 303 303 302]
 [318 319 320 ... 306 302 302]
 [321 321 322 ... 308 305 303]
 ...
 [391 392 394 ... 379 377 373]
 [390 391 391 ... 379 376 374]
 [389 390 390 ... 378 372 372]]
1001
(355, 266)


In [11]:
#o=data[:0,0]で0*0のpixのtime-sereiesを取り出す
o=data[:,0,0]
print(o)
print(o.shape)
o=data[:,354,265]
print("354*265",o)#last pix


[314 315 315 ... 312 311 311]
(1001,)
354*265 [381 378 379 ... 370 370 370]


In [ ]:
To get colliration of A , B

A 


In [4]:
hdfpath=
with h5py.File(hdfpath,'r') as f:
    # ファイルオブジェクトをイテレートするとファイル直下のオブジェクト名を返す
    data=f['/Object'][0]
print(data.shape)    

(1001, 355, 266)


In [15]:
import itertools
for x, y in itertools.product(range(10), range(10)):
    print(x,y)
test = np.array([[1,2,3],[4,5,6],[7,8,9]])


[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]


In [93]:
test_array = np.array([[[1,2],[3,4]],[[11,12],[13,14]],[[21,22],[23,100]]])
print(test_array)
splited = np.split(test_array,2,axis=1)
print("\n")
print("splited",splited)

[[[  1   2]
  [  3   4]]

 [[ 11  12]
  [ 13  14]]

 [[ 21  22]
  [ 23 100]]]


splited [array([[[ 1,  2]],

       [[11, 12]],

       [[21, 22]]]), array([[[  3,   4]],

       [[ 13,  14]],

       [[ 23, 100]]])]


In [77]:
test = np.array([[[1,2],[3,4]],[[11,12],[13,14]],[[21,22],[23,100]]])
print(test)

test_list=[]
for i, j in itertools.product(range(2), range(2)):
    print(i,j)
    test_list.append(test[:,i,j])
print(test_list)    

[[[  1   2]
  [  3   4]]

 [[ 11  12]
  [ 13  14]]

 [[ 21  22]
  [ 23 100]]]
0 0
0 1
1 0
1 1


AttributeError: 'list' object has no attribute 'split'

In [60]:
a = list[0]
b = list[3]

I = [a,b]
r = np.corrcoef(I)
print(r)

[[1.         0.90949989]
 [0.90949989 1.        ]]


In [10]:
x = data[:,0,0]
y = data[:,177,132]
z = data[:,354,265]

a = [x,y,z]

r = np.corrcoef(a)

print(r)

[[1.         0.62112803 0.06451254]
 [0.62112803 1.         0.46427402]
 [0.06451254 0.46427402 1.        ]]


In [63]:
list=[]
for x, y in itertools.product(range(354), range(265)):
    list.append(data[:,x,y])
    
print(len(list))
print(354*265)
print("listはかなり大きいのでメモリに気を使うこと")

93810
93810


In [104]:
np.set_printoptions(threshold=100)
batch=[]
for x, y in itertools.product(range(10), range(10)):
    batch.append(data[:,x,y])
    #print(x,y)

r = np.corrcoef(batch)
print(r)
print(len(r))
#print(len(batch[0]))

[[1.         0.88103337 0.80628423 ... 0.80253051 0.79921869 0.80909786]
 [0.88103337 1.         0.88861751 ... 0.79413128 0.78450645 0.78935385]
 [0.80628423 0.88861751 1.         ... 0.79185756 0.78016244 0.7783479 ]
 ...
 [0.80253051 0.79413128 0.79185756 ... 1.         0.92936093 0.86177062]
 [0.79921869 0.78450645 0.78016244 ... 0.92936093 1.         0.9221382 ]
 [0.80909786 0.78935385 0.7783479  ... 0.86177062 0.9221382  1.        ]]
100


In [75]:
#print(list[100])
#print(list[200])
print(6*59,5*53)

354 265


In [119]:
class MyClass:
    def function(self):
        print('Hello,Pythonのオブジェクト指向')



In [139]:
import matplotlib.pyplot as plt

class colfig:
    def figs(self):
        plt.figure(figsize=(20,5))
        figsize=(100,100)
        plt.xlim(0,1000) 
        plt.plot(self)
        plt.show()
    def compare(s,t):
        #print(s,t)
        r = np.corrcoef(s,t)
        print(r)
        figs(s)
        figs(t)
        
        

s = list[0]
t = list[1]

#colfig.compare(s,t)


    
    

#93810

#figs(list[0])
#figs(list[1])
#figs(list[93809])

In [109]:
r = np.corrcoef(s,t)
print(r)

[[ 1.         -0.01751102]
 [-0.01751102  1.        ]]


In [107]:
#pixの相関係数の高いものを検出する >> Ca+の反応場所
#354*265は大きすぎるので59分割×53分割して6*5を最小単位とするバッチで処理する (6*59=354\5*53=265)
print(354*265)

93810
